Bugfix/314 in user status response 401 unauthorized need 403 forbidden resolve
GreenCityProject/GreenCityUser21_team1_August pull request #11
Opened 2024-08-15 13:30 UTC by NazarVavrushchak

2024-08-16 09:56 UTC, vulook approved these changes
That works

2024-08-17 20:14 UTC, ZenukD approved these changes

2024-08-26 20:48 UTC, ChernenkoVitaliy requested changes

2024-08-26 20:48 UTC, ChernenkoVitaliy commented on core/src/main/java/greencity/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
In my opinion, this block if(principal == null) doesn't make any sense. In SecuritiConfig configured that only ADMIN can reach this endpoint. It means the principal can't be null!

Also, task 314 says "Sign-in us user". According to SecurityConfig this endpoint can't reach anybody except ADMIN.

I was trying to sign in as USER and enter valid data. And I received 401. But expected 403.
Please fix it.

2024-08-26 20:49 UTC, ChernenkoVitaliy commented
> That works

No, it doesn't)))

2024-09-19 18:59 UTC, VitaliiChernenko approved these changes

2024-09-19 19:03 UTC, ChernenkoVitaliy commented
Now there is nothing to commit. Except for changing the formatting code, I do not see nothing in this PR. I guess the bug from task 314 was accidentally solved by another PR.  You can just close the PR without merging.

2024-09-20 05:37 UTC, closed without merging

2024-09-20 05:58 UTC, vulook reviewed
It looks okay